import { useCallback, useEffect, useRef, useState } from "react";
import type { ApiResult, DocumentFile, EntityStatus, Folder, Project, SearchResult, VaultLifecycleState, VaultSnapshot } from "@orbit/vault-types";
import GraphViewV2 from "./GraphViewV2";
import KnowledgeView from "./KnowledgeView";
import BackupsView from "./BackupsView";
import ProjectContextView from "./ProjectContextView";

const unwrap = <T,>(result: ApiResult<T>) => { if (!result.ok) throw new Error(result.error.message); return result.value; };
type ViewStatus = "active" | "archived" | "trashed";
type SaveState = "idle" | "edited" | "saving" | "saved" | "failed";
type TextDialog = { title: string; value: string; resolve: (value: string | null) => void };

export default function App() {
  const [snapshot, setSnapshot] = useState<VaultSnapshot | null>(null);
  const [lifecycle, setLifecycle] = useState<VaultLifecycleState | null>(null);
  const [allProjects, setAllProjects] = useState<Project[]>([]);
  const [projectId, setProjectId] = useState<string | null>(null);
  const [folders, setFolders] = useState<Folder[]>([]);
  const [documents, setDocuments] = useState<DocumentFile[]>([]);
  const [folderId, setFolderId] = useState<string | null>(null);
  const [document, setDocument] = useState<DocumentFile | null>(null);
  const [content, setContent] = useState(""); const [savedContent, setSavedContent] = useState("");
  const [saveState, setSaveState] = useState<SaveState>("idle");
  const [view, setView] = useState<"files" | "knowledge" | "atlas" | "backups" | "context">("files"); const [statusView, setStatusView] = useState<ViewStatus>("active");
  const [knowledgeFocusId,setKnowledgeFocusId]=useState<string|null>(null);
  const [query, setQuery] = useState(""); const [results, setResults] = useState<SearchResult[]>([]); const [error, setError] = useState("");
  const [syncMessage,setSyncMessage]=useState("");
  const [textDialog, setTextDialog] = useState<TextDialog | null>(null);
  const documentRef = useRef<DocumentFile | null>(null); const contentRef = useRef(""); const savedRef = useRef(""); const savingRef = useRef<Promise<boolean> | null>(null);
  const dirty = content !== savedContent;

  useEffect(() => { documentRef.current = document; }, [document]); useEffect(() => { contentRef.current = content; }, [content]); useEffect(() => { savedRef.current = savedContent; }, [savedContent]);
  const showError = useCallback((reason: unknown) => setError(reason instanceof Error ? reason.message : String(reason)),[]);
  const requestText = (title: string, value = "") => new Promise<string | null>(resolve => setTextDialog({ title, value, resolve }));
  const closeTextDialog = (value: string | null) => { const dialog=textDialog; setTextDialog(null); dialog?.resolve(value?.trim() || null); };
  const refresh = useCallback(async () => { try { const [next, state, active, archived, trashed] = await Promise.all([window.vault.snapshot(), window.vault.lifecycle.state(), window.vault.projects.list({status:"active"}), window.vault.projects.list({status:"archived"}), window.vault.projects.list({status:"trashed"})]); setSnapshot(unwrap(next)); setLifecycle(unwrap(state)); const projects=[...unwrap(active),...unwrap(archived),...unwrap(trashed)]; setAllProjects(projects); setProjectId(id => id && projects.some(p=>p.id===id) ? id : projects.find(p=>p.status==="active")?.id ?? projects[0]?.id ?? null); setError(""); } catch (reason) { showError(reason); } }, []);
  useEffect(() => { void refresh(); const offChanged=window.vault.onChanged(()=>void refresh()); return offChanged; }, [refresh]);
  useEffect(() => { if (!projectId) { setFolders([]); setDocuments([]); return; } void Promise.all([window.vault.folders.list(projectId),window.vault.documents.list(projectId)]).then(([a,b])=>{setFolders(unwrap(a));setDocuments(unwrap(b));}).catch(showError); }, [projectId,snapshot]);

  const saveNow = useCallback(async () => {
    if (savingRef.current) return savingRef.current; const current=documentRef.current, nextContent=contentRef.current;
    if (!current || nextContent===savedRef.current) return true;
    const operation=(async()=>{setSaveState("saving");try{const updated=unwrap(await window.vault.documents.updateContent(current.id,nextContent));if(documentRef.current?.id===current.id){setDocument(updated);setSavedContent(nextContent);savedRef.current=nextContent;setSaveState("saved");}return true;}catch(reason){showError(reason);setSaveState("failed");return false;}finally{savingRef.current=null;}})(); savingRef.current=operation; return operation;
  }, []);
  useEffect(() => { if (!document || !dirty) return; setSaveState("edited"); const timer=setTimeout(()=>void saveNow(),700); return()=>clearTimeout(timer); },[content,document,dirty,saveNow]);
  useEffect(() => { const key=(event:KeyboardEvent)=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="s"){event.preventDefault();void saveNow();}}; const unload=(event:BeforeUnloadEvent)=>{if(contentRef.current!==savedRef.current){event.preventDefault();event.returnValue="";}}; addEventListener("keydown",key);addEventListener("beforeunload",unload);return()=>{removeEventListener("keydown",key);removeEventListener("beforeunload",unload);};},[saveNow]);
  const beforeNavigate=async()=>await saveNow();
  const runLifecycle=useCallback(async(action:"create"|"open")=>{if(!(await saveNow()))return;try{const state=unwrap(await window.vault.lifecycle[action]());if(state){setLifecycle(state);setDocument(null);setContent("");setSavedContent("");setFolderId(null);await refresh();}}catch(reason){showError(reason);}},[refresh,saveNow]);
  useEffect(()=>window.vault.onLifecycleRequest(action=>void runLifecycle(action)),[runLifecycle]);

  useEffect(()=>{const timer=setTimeout(()=>{if(!query.trim())return setResults([]);void window.vault.search.query({query,limit:30}).then(value=>setResults(unwrap(value))).catch(showError);},180);return()=>clearTimeout(timer);},[query,snapshot]);
  const currentProject=allProjects.find(item=>item.id===projectId);
  const visibleProjects=statusView==="active"?allProjects.filter(p=>p.status==="active"):allProjects;
  const visibleFolders=folders.filter(item=>item.status===statusView || (statusView!=="active" && item.status==="active"));
  const visibleDocuments=documents.filter(item=>item.status===statusView && item.parentFolderId===folderId);
  const selectProject=async(id:string)=>{if(!(await beforeNavigate()))return;setProjectId(id);setFolderId(null);setDocument(null);setContent("");setSavedContent("");setSaveState("idle");};
  const chooseDocument=async(next:DocumentFile)=>{if(!(await beforeNavigate()))return;try{if(next.kind==="file"){setDocument(next);setContent("");setSavedContent("");savedRef.current="";setSaveState("idle");setView("files");return;}const value=unwrap(await window.vault.documents.read(next.id));setDocument(value.document);setContent(value.content);setSavedContent(value.content);savedRef.current=value.content;setSaveState("saved");setView("files");}catch(reason){showError(reason);}};
  const mutate=async(operation:()=>Promise<ApiResult<unknown>>)=>{try{unwrap(await operation());await refresh();}catch(reason){showError(reason);}};

  const createProject=async()=>{const name=await requestText("Create project");if(name)try{const project=unwrap(await window.vault.projects.create({name}));await refresh();setProjectId(project.id);setStatusView("active");}catch(reason){showError(reason);}};
  const renameProject=async()=>{if(!currentProject)return;const name=await requestText("Rename project",currentProject.name);if(name)await mutate(()=>window.vault.projects.update(currentProject.id,{name}));};
  const setProjectStatus=async(status:EntityStatus)=>{if(!currentProject)return;if(!(await beforeNavigate()))return;if((status!=="active")&&!confirm(`${status==="trashed"?"Move":"Archive"} ${currentProject.name} and all of its contents?`))return;await mutate(()=>status==="active"?window.vault.projects.restore(currentProject.id):status==="archived"?window.vault.projects.archive(currentProject.id):window.vault.projects.trash(currentProject.id));setDocument(null);setFolderId(null);setStatusView(status);};
  const createFolder=async()=>{if(!projectId)return;const name=await requestText(folderId?"Create nested folder":"Create folder");if(name)await mutate(()=>window.vault.folders.create({projectId,parentFolderId:folderId,name}));};
  const selectedFolder=folders.find(item=>item.id===folderId);
  const selectFolder=async(id:string|null)=>{if(!(await beforeNavigate()))return;setFolderId(id);setDocument(null);setContent("");setSavedContent("");setSaveState("idle");};
  const changeStatusView=async(status:ViewStatus)=>{if(!(await beforeNavigate()))return;setStatusView(status);setFolderId(null);setDocument(null);setContent("");setSavedContent("");setSaveState("idle");};
  const renameFolder=async()=>{if(!selectedFolder)return;const name=await requestText("Rename folder",selectedFolder.name);if(name)await mutate(()=>window.vault.folders.rename(selectedFolder.id,name));};
  const moveFolder=async(parent:string)=>{if(selectedFolder)await mutate(()=>window.vault.folders.move(selectedFolder.id,parent||null));};
  const setFolderStatus=async(status:EntityStatus)=>{if(!selectedFolder)return;if(status!=="active"&&!confirm(`${status==="trashed"?"Move":"Archive"} ${selectedFolder.name} and all descendants?`))return;await mutate(()=>status==="active"?window.vault.folders.restore(selectedFolder.id):status==="archived"?window.vault.folders.archive(selectedFolder.id):window.vault.folders.trash(selectedFolder.id));setFolderId(null);setDocument(null);setStatusView(status);};
  const createNote=async()=>{if(!projectId)return;const title=await requestText("Create Markdown note","Untitled.md");if(title)try{const note=unwrap(await window.vault.documents.createMarkdown({projectId,parentFolderId:folderId,title}));await refresh();await chooseDocument(note);}catch(reason){showError(reason);}};
  const importFiles=async()=>{if(!projectId||statusView!=="active")return;try{const sourcePaths=await window.orbit.desktop.openFiles();if(!sourcePaths.length)return;const imported=unwrap(await window.vault.documents.importFiles({projectId,parentFolderId:folderId,sourcePaths}));await refresh();if(imported[0])await chooseDocument(imported[0]);}catch(reason){showError(reason);}};
  const reconcileFilesystem=async()=>{try{const report=unwrap(await window.vault.filesystem.reconcile());await refresh();setSyncMessage(`${report.projectsAdded} projects added · ${report.projectsArchived} removed projects archived · ${report.foldersAdded} folders · ${report.documentsAdded} files added`);setTimeout(()=>setSyncMessage(""),6000);}catch(reason){showError(reason);}};
  const renameDocument=async()=>{if(!document)return;const title=await requestText("Rename note",document.title);if(title)try{const next=unwrap(await window.vault.documents.rename(document.id,title));setDocument(next);await refresh();}catch(reason){showError(reason);}};
  const moveDocument=async(parent:string)=>{if(document)try{const next=unwrap(await window.vault.documents.move(document.id,parent||null));setDocument(next);setFolderId(next.parentFolderId);await refresh();}catch(reason){showError(reason);}};
  const setDocumentStatus=async(status:EntityStatus)=>{if(!document)return;if(!(await beforeNavigate()))return;if(status!=="active"&&!confirm(`${status==="trashed"?"Move":"Archive"} ${document.title}?`))return;await mutate(()=>status==="active"?window.vault.documents.restore(document.id):status==="archived"?window.vault.documents.archive(document.id):window.vault.documents.trash(document.id));setDocument(null);setContent("");setSavedContent("");setStatusView(status);};
  const switchVault=async(path:string)=>{if(!(await beforeNavigate()))return;try{setLifecycle(unwrap(await window.vault.lifecycle.switch(path)));setDocument(null);setFolderId(null);setProjectId(null);await refresh();}catch(reason){showError(reason);}};
  const chooseResult=async(result:SearchResult)=>{await selectProject(result.projectId);setQuery("");setResults([]);if(result.entityType==="knowledge"){setKnowledgeFocusId(result.id);setView("knowledge");return;}const item=(snapshot?.documents??[]).find(doc=>doc.id===result.id);if(item){setFolderId(item.parentFolderId);await chooseDocument(item);}else if(result.entityType==="folder")setFolderId(result.id);else setView("atlas");};
  const openEvidenceDocument=(id:string)=>{const item=(snapshot?.documents??[]).find(doc=>doc.id===id);if(item){setFolderId(item.parentFolderId);void chooseDocument(item);}};

  return <div className="vault-app">
    {view==="files"&&<button className="source-import" onClick={()=>void importFiles()} disabled={!projectId||statusView!=="active"}>Import files…</button>}
    <div className="filesystem-actions"><button onClick={()=>void window.vault.filesystem.openProjectsFolder().then(unwrap).catch(showError)}>Open Projects Folder</button><button onClick={()=>void reconcileFilesystem()}>Refresh from Disk</button></div>{syncMessage&&<div className="sync-message">{syncMessage}</div>}
    {document?.kind==="file"&&view==="files"&&<section className="attachment-inspector"><div className="attachment-icon">{document.availability==="missing"?"!":"◇"}</div><h2>{document.title}</h2><p>{document.relativePath}</p><dl><div><dt>Type</dt><dd>{document.mimeType??"File"}</dd></div><div><dt>Status</dt><dd>{document.availability}</dd></div><div><dt>Storage</dt><dd>Managed by this Vault</dd></div></dl><div className="attachment-actions"><button className="primary" disabled={document.availability==="missing"} onClick={()=>void window.vault.documents.open(document.id).then(unwrap).catch(showError)}>Open file</button><button disabled={document.availability==="missing"} onClick={()=>void window.vault.documents.reveal(document.id).then(unwrap).catch(showError)}>Show in Explorer</button><button onClick={()=>void renameDocument()}>Rename</button><select value={document.parentFolderId??""} onChange={event=>void moveDocument(event.target.value)}><option value="">Project root</option>{folders.filter(f=>f.status==="active").map(f=><option value={f.id} key={f.id}>{f.relativePath}</option>)}</select>{document.status==="active"?<><button onClick={()=>void setDocumentStatus("archived")}>Archive</button><button onClick={()=>void setDocumentStatus("trashed")}>Trash</button></>:<button onClick={()=>void setDocumentStatus("active")}>Restore</button>}</div>{document.availability==="missing"&&<div className="missing-warning">The managed source file is missing from Vault storage. Its metadata and links remain intact.</div>}</section>}
    <header className="vault-top"><div className="brand"><span className="brand-mark">O</span><span>Orbit Vault</span><span className="crumb">/ {lifecycle?.active.name??"Vault"} / {currentProject?.name??"No project"}</span></div><div className="view-switch"><button className={view==="files"?"active":""} onClick={()=>setView("files")}>Files</button><button className={view==="knowledge"?"active":""} onClick={()=>setView("knowledge")}>Knowledge</button><button className={view==="atlas"?"active":""} onClick={()=>setView("atlas")}>Atlas</button><button className={view==="backups"?"active":""} onClick={()=>setView("backups")}>Backups</button><button className={view==="context"?"active":""} onClick={()=>setView("context")}>Context</button></div><div className={`save-state ${saveState}`}>{saveState==="saving"?"Saving…":saveState==="failed"?"Save failed":dirty?"Edited":document?"Saved locally":"Local-first"}</div></header>
    <aside className="vault-sidebar"><div className="vault-picker"><b>{lifecycle?.active.name}</b><small title={lifecycle?.active.path}>{lifecycle?.active.path}</small><div><button onClick={()=>void runLifecycle("create")}>Create</button><button onClick={()=>void runLifecycle("open")}>Open</button></div><select value={lifecycle?.active.path??""} onChange={event=>void switchVault(event.target.value)}>{lifecycle?.recent.map(item=><option value={item.path} key={item.path}>{item.name}</option>)}</select></div><button className="new-note" onClick={()=>void createNote()} disabled={!projectId||statusView!=="active"}>+ New note</button><div className="status-tabs">{(["active","archived","trashed"] as ViewStatus[]).map(status=><button className={statusView===status?"active":""} onClick={()=>void changeStatusView(status)} key={status}>{status==="trashed"?"Trash":status[0].toUpperCase()+status.slice(1)}</button>)}</div><div className="section-label">Projects <button onClick={()=>void createProject()} disabled={statusView!=="active"}>+</button></div>{visibleProjects.map(project=><button className={`nav-item ${project.id===projectId?"active":""}`} key={project.id} onClick={()=>void selectProject(project.id)}><span style={{color:project.color??"#8fa7ff"}}>●</span>{project.name}<b>{project.status!=="active"?project.status:""}</b></button>)}<div className="section-label">Folders <button onClick={()=>void createFolder()} disabled={!projectId||statusView!=="active"}>+</button></div><button className={`folder ${folderId===null?"active":""}`} onClick={()=>void selectFolder(null)}>⌂ Project root</button>{visibleFolders.map(folder=><button className={`folder ${folder.id===folderId?"active":""}`} key={folder.id} onClick={()=>void selectFolder(folder.id)} style={{paddingLeft:12+folder.relativePath.split("/").length*9}}>▸ {folder.name}</button>)}<div className="vault-status"><span className="status-dot"/>Vault online<small>{documents.filter(d=>d.status==="active").length} active documents</small></div></aside>
    <main className="vault-main">{view==="files"&&<div className="vault-search"><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search titles and Markdown content…"/>{query&&<div className="search-results">{results.map(result=><button key={`${result.entityType}-${result.id}`} onClick={()=>void chooseResult(result)}><b>{result.title}</b><small>{result.path}</small>{result.excerpt&&<small>{result.excerpt}</small>}</button>)}{results.length===0&&<p>No results</p>}</div>}</div>}{error&&<div className="error-banner">{error}<button onClick={()=>setError("")}>×</button></div>}
      {snapshot&&view==="knowledge"&&<div className="knowledge-overlay"><KnowledgeView snapshot={snapshot} project={currentProject??null} selectedId={knowledgeFocusId} onSelected={setKnowledgeFocusId} onChanged={refresh} onError={showError} onOpenDocument={openEvidenceDocument}/></div>}
      {snapshot&&view==="backups"&&<div className="backups-overlay"><BackupsView onError={showError} beforeSnapshot={saveNow}/></div>}
      {snapshot&&view==="context"&&<div className="context-overlay">{currentProject?<ProjectContextView projectId={currentProject.id} onError={showError}/>:<div className="empty-state">Select a project to analyze its context.</div>}</div>}
      {!snapshot?<div className="empty-state">Opening Vault…</div>:view==="atlas"?<GraphViewV2 snapshot={snapshot} onOpen={chooseResult}/>:<div className="files-layout"><section className="file-list"><div className="file-list-head"><b>{selectedFolder?.name??currentProject?.name??"No project"}</b>{statusView==="active"&&<button onClick={()=>void createNote()}>+ Note</button>}</div>{visibleDocuments.map(item=><button className={item.id===document?.id?"selected":""} key={item.id} onClick={()=>void chooseDocument(item)}><span>◇</span><span><b>{item.title}</b><small>{item.relativePath}</small></span></button>)}{visibleDocuments.length===0&&<p className="list-empty">No {statusView} documents here.</p>}</section><section className="editor">{document?<><div className="editor-bar"><b>{document.title}</b><span>{saveState}</span>{document.status==="active"?<><button onClick={()=>void renameDocument()}>Rename</button><select value={document.parentFolderId??""} onChange={event=>void moveDocument(event.target.value)}><option value="">Project root</option>{folders.filter(f=>f.status==="active").map(f=><option value={f.id} key={f.id}>{f.relativePath}</option>)}</select><button onClick={()=>void setDocumentStatus("archived")}>Archive</button><button onClick={()=>void setDocumentStatus("trashed")}>Trash</button><button className="primary" disabled={!dirty} onClick={()=>void saveNow()}>Save</button></>:<button className="primary" onClick={()=>void setDocumentStatus("active")}>Restore</button>}</div><textarea value={content} onChange={event=>setContent(event.target.value)} readOnly={document.status!=="active"} spellCheck={false}/></>:<div className="empty-editor"><h2>{statusView==="active"?"Select a note":"Archive and Trash"}</h2><p>{statusView==="active"?"Markdown autosaves locally after a short pause.":"Select an item to inspect or restore it."}</p>{selectedFolder&&<div className="folder-actions">{selectedFolder.status==="active"?<><button onClick={()=>void renameFolder()}>Rename folder</button><select value={selectedFolder.parentFolderId??""} onChange={event=>void moveFolder(event.target.value)}><option value="">Project root</option>{folders.filter(f=>f.status==="active"&&f.id!==selectedFolder.id).map(f=><option value={f.id} key={f.id}>{f.relativePath}</option>)}</select><button onClick={()=>void setFolderStatus("archived")}>Archive</button><button onClick={()=>void setFolderStatus("trashed")}>Trash</button></>:<button onClick={()=>void setFolderStatus("active")}>Restore folder</button>}</div>}{currentProject&&<div className="project-actions"><button onClick={()=>void renameProject()}>Rename project</button>{currentProject.status==="active"?<><button onClick={()=>void setProjectStatus("archived")}>Archive project</button><button onClick={()=>void setProjectStatus("trashed")}>Trash project</button></>:<button onClick={()=>void setProjectStatus("active")}>Restore project</button>}</div>}</div>}</section></div>}
    </main>{textDialog&&<div className="dialog-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)closeTextDialog(null)}}><form className="text-dialog" onSubmit={event=>{event.preventDefault();closeTextDialog(textDialog.value)}}><h2>{textDialog.title}</h2><input autoFocus value={textDialog.value} onChange={event=>setTextDialog({...textDialog,value:event.target.value})} onFocus={event=>event.currentTarget.select()} onKeyDown={event=>{if(event.key==="Escape")closeTextDialog(null)}}/><div><button type="button" onClick={()=>closeTextDialog(null)}>Cancel</button><button className="primary" type="submit" disabled={!textDialog.value.trim()}>Save</button></div></form></div>}
  </div>;
}
