import { useEffect, useMemo, useRef, useState } from "react";
import { forceSimulation, forceX, forceY, forceCollide, forceManyBody, forceLink } from "d3-force";
import type { SearchResult, VaultSnapshot } from "@orbit/vault-types";
import { ancestorIds, assertHierarchyModel, createHierarchyModel, isHiddenByCollapse, type GraphNode } from "./hierarchyGraph";

type Command={type:"zoom-in"|"zoom-out"|"fit"|"center"|"reset"}|{type:"focus";id:string};
const clamp=(value:number,min:number,max:number)=>Math.min(max,Math.max(min,value));
const PALETTE=["#6d8cff","#f0b45b","#8ad6a5","#e88498","#a88ff0","#67c5d8"];
const colorFor=(id:string)=>PALETTE[[...id].reduce((sum,char)=>sum+char.charCodeAt(0),0)%PALETTE.length];

export default function GraphViewV2({snapshot,onOpen}:{snapshot:VaultSnapshot;onOpen:(result:SearchResult)=>void}){
  const model=useMemo(()=>{const next=createHierarchyModel(snapshot.atlasNodes);assertHierarchyModel(next);return next;},[snapshot]);
  const canvasRef=useRef<HTMLCanvasElement>(null);const nodesRef=useRef(model.nodes.map(node=>({...node})));const cameraRef=useRef({x:0,y:0,scale:1});
  const selectedRef=useRef<GraphNode|null>(null);const hoveredRef=useRef<GraphNode|null>(null);
  const[query,setQuery]=useState("");const[selected,setSelected]=useState<GraphNode|null>(null);const[hovered,setHovered]=useState<GraphNode|null>(null);
  const maxDepth=Math.max(1,...model.nodes.map(node=>node.depth));
  const[collapsed,setCollapsed]=useState(()=>new Set(model.nodes.filter(node=>node.type==="folder"&&node.depth>=2&&node.childCount>0).map(node=>node.id)));const[motion,setMotion]=useState(true);const[labels,setLabels]=useState(true);const[panel,setPanel]=useState(true);
  const[nodeSize,setNodeSize]=useState(100);const[linkStrength,setLinkStrength]=useState(62);const[repelStrength,setRepelStrength]=useState(34);const[depthLimit,setDepthLimit]=useState(maxDepth);const[zoom,setZoom]=useState(100);const[localMode,setLocalMode]=useState(false);const[showConnections,setShowConnections]=useState(false);const[showKnowledge,setShowKnowledge]=useState(true);
  const branches=useMemo(()=>model.nodes.filter(node=>node.depth===1),[model]);const[activeBranches,setActiveBranches]=useState(()=>new Set(branches.map(node=>node.id)));
  useEffect(()=>{nodesRef.current=model.nodes.map(node=>({...node}));setSelected(null);setHovered(null);setCollapsed(new Set(model.nodes.filter(node=>node.type==="folder"&&node.depth>=2&&node.childCount>0).map(node=>node.id)));setMotion(true);setDepthLimit(Math.max(1,...model.nodes.map(node=>node.depth)));setActiveBranches(new Set(model.nodes.filter(node=>node.depth===1).map(node=>node.id)));requestAnimationFrame(()=>command({type:"fit"}));},[model]);
  useEffect(()=>{selectedRef.current=selected;},[selected]);useEffect(()=>{hoveredRef.current=hovered;},[hovered]);
  const normalized=query.trim().toLowerCase();const results=useMemo(()=>normalized?model.nodes.filter(node=>node.name.toLowerCase().includes(normalized)||node.path.toLowerCase().includes(normalized)).slice(0,10):[],[model,normalized]);
  const command=(detail:Command)=>canvasRef.current?.dispatchEvent(new CustomEvent<Command>("graph-command",{detail}));
  const focus=(node:GraphNode)=>{const ancestors=ancestorIds(node,model.nodeById);setCollapsed(previous=>{const next=new Set(previous);ancestors.forEach(id=>next.delete(id));return next;});setSelected(node);setQuery(node.name);command({type:"focus",id:node.id});};
  const toggleBranch=(id:string)=>setActiveBranches(previous=>{const next=new Set(previous);next.has(id)?next.delete(id):next.add(id);return next;});
  const openNode=(node:GraphNode)=>node.type!=="vault"&&onOpen({id:node.id,entityType:node.type==="file"?"document":node.type,projectId:node.projectId??node.id,projectName:"",title:node.name,path:node.path,excerpt:null});

  useEffect(()=>{const canvas=canvasRef.current,context=canvas?.getContext("2d");if(!canvas||!context)return;let frame=0,width=0,height=0,pointerId:number|null=null,dragged:GraphNode|null=null,panning=false,moved=false,last={x:0,y:0};
    const nodeById=new Map(nodesRef.current.map(node=>[node.id,node]));const children=new Map<string,GraphNode[]>();nodesRef.current.forEach(node=>{if(node.parentId)children.set(node.parentId,[...(children.get(node.parentId)??[]),node]);});
    const descendants=(node:GraphNode)=>{const found:GraphNode[]=[];const visit=(id:string)=>(children.get(id)??[]).forEach(child=>{found.push(child);visit(child.id);});visit(node.id);return found;};
    let forcedKey="",forcedValue=new Set<string>();const forced=()=>{const chosen=selectedRef.current,key=`${normalized}|${chosen?.id??""}|${showConnections}`;if(key===forcedKey)return forcedValue;const ids=new Set<string>();nodesRef.current.filter(node=>normalized&&(node.name.toLowerCase().includes(normalized)||node.path.toLowerCase().includes(normalized))).forEach(node=>{ids.add(node.id);ancestorIds(node,nodeById).forEach(id=>ids.add(id));});if(chosen){ids.add(chosen.id);ancestorIds(chosen,nodeById).forEach(id=>ids.add(id));descendants(chosen).forEach(node=>ids.add(node.id));if(showConnections)snapshot.relationships.filter(edge=>edge.sourceId===chosen.id||edge.targetId===chosen.id).forEach(edge=>{const connected=nodeById.get(edge.sourceId===chosen.id?edge.targetId:edge.sourceId);if(connected){ids.add(connected.id);ancestorIds(connected,nodeById).forEach(id=>ids.add(id));}});}forcedKey=key;forcedValue=ids;return ids;};
    const noForce=new Set<string>();const visible=(node:GraphNode,candidate?:Set<string>|number)=>{const force=candidate instanceof Set?candidate:(normalized||selectedRef.current?forced():noForce);if(node.depth===0)return true;if(node.type==="knowledge"&&!showKnowledge&&!force.has(node.id))return false;if(!activeBranches.has(node.branchId))return false;if((node.depth>depthLimit||isHiddenByCollapse(node,collapsed,nodeById))&&!force.has(node.id))return false;if(localMode&&selectedRef.current&&!force.has(node.id))return false;return true;};
    const resize=()=>{const box=canvas.getBoundingClientRect(),ratio=Math.min(devicePixelRatio,2);width=box.width;height=box.height;canvas.width=Math.round(width*ratio);canvas.height=Math.round(height*ratio);context.setTransform(ratio,0,0,ratio,0,0);};resize();const observer=new ResizeObserver(resize);observer.observe(canvas);
    const point=(event:PointerEvent|WheelEvent)=>{const box=canvas.getBoundingClientRect();return{x:event.clientX-box.left-width/2,y:event.clientY-box.top-height/2};};const world=(p:{x:number;y:number})=>({x:(p.x-cameraRef.current.x)/cameraRef.current.scale,y:(p.y-cameraRef.current.y)/cameraRef.current.scale});
    const hit=(p:{x:number;y:number})=>{const w=world(p);return[...nodesRef.current].reverse().find(node=>visible(node)&&Math.hypot(node.x-w.x,node.y-w.y)<node.radius*nodeSize/100+8/cameraRef.current.scale)??null;};
    const scaleTo=(next:number,anchor={x:0,y:0})=>{const camera=cameraRef.current,scale=clamp(next,.2,4),wx=(anchor.x-camera.x)/camera.scale,wy=(anchor.y-camera.y)/camera.scale;camera.x=anchor.x-wx*scale;camera.y=anchor.y-wy*scale;camera.scale=scale;setZoom(Math.round(scale*100));};
    const fit=()=>{const shown=nodesRef.current.filter(visible);if(!shown.length)return;const minX=Math.min(...shown.map(n=>n.x-n.radius)),maxX=Math.max(...shown.map(n=>n.x+n.radius)),minY=Math.min(...shown.map(n=>n.y-n.radius)),maxY=Math.max(...shown.map(n=>n.y+n.radius));const scale=clamp(Math.min((width-100)/Math.max(1,maxX-minX),(height-110)/Math.max(1,maxY-minY)),.25,2.2);cameraRef.current.x=-(minX+maxX)/2*scale;cameraRef.current.y=-(minY+maxY)/2*scale;cameraRef.current.scale=scale;setZoom(Math.round(scale*100));};

    // A single d3-force simulation replaces what used to be two independent
    // requestAnimationFrame loops (a hand-rolled repulsion pass, and a separate
    // spring-to-target integration inside the draw loop) fighting over the same
    // node.x/y/vx/vy every frame. Now there's one force graph: forceX/forceY pull
    // every node toward its deterministic hierarchyGraph position (the "Hierarchy
    // pull" slider), forceCollide resolves actual overlaps (the "Node size"
    // slider feeds its radius), a short-range forceManyBody adds a little
    // breathing room between near neighbours (the "Node spacing" slider), and a
    // weak forceLink along the "contains" edges is what makes a dragged node's
    // children drift along with it — elastically, the way linked nodes do in any
    // d3-force graph, not rigidly pinned in lockstep. draw() below only reads
    // node.x/y to paint — it never moves anything itself.
    const structuralLinks=model.structuralEdges.map(edge=>{const source=nodeById.get(edge.sourceId),target=nodeById.get(edge.targetId);return{source:edge.sourceId,target:edge.targetId,id:edge.id,distance:source&&target?Math.hypot(source.targetX-target.targetX,source.targetY-target.targetY):48};});
    const collideRadius=(node:GraphNode)=>node.radius*(nodeSize/100)+5+(repelStrength/100)*14;
    const simulation=forceSimulation(nodesRef.current)
      .alphaDecay(0.03)
      .velocityDecay(0.32)
      .force("link",forceLink<GraphNode,typeof structuralLinks[number]>(structuralLinks).id(node=>node.id).distance(link=>link.distance).strength(link=>{const target=typeof link.target==="string"?nodeById.get(link.target):link.target;return target?.depth===1?.015+(linkStrength/100)*.02:.06+(linkStrength/100)*.2;}))
      .force("x",forceX<GraphNode>(node=>node.clusterX).strength(node=>node.depth===0?.008:node.depth===1?.1+(linkStrength/100)*.1:.012+(linkStrength/100)*.035))
      .force("y",forceY<GraphNode>(node=>node.clusterY).strength(node=>node.depth===0?.008:node.depth===1?.1+(linkStrength/100)*.1:.012+(linkStrength/100)*.035))
      .force("collide",forceCollide<GraphNode>(collideRadius).strength(0.85).iterations(3))
      .force("spacing",forceManyBody<GraphNode>().strength(-18-(repelStrength/100)*64).distanceMin(8).distanceMax(220))
      .alpha(0.7);
    if(!motion)simulation.stop();

    const pin=(node:GraphNode,x:number,y:number)=>{node.fx=x;node.fy=y;node.x=x;node.y=y;};
    const unpin=(node:GraphNode)=>{node.fx=null;node.fy=null;};
    const onCommand=(event:Event)=>{const detail=(event as CustomEvent<Command>).detail;if(detail.type==="zoom-in")scaleTo(cameraRef.current.scale*1.22);if(detail.type==="zoom-out")scaleTo(cameraRef.current.scale/1.22);if(detail.type==="fit")fit();if(detail.type==="center"){cameraRef.current.x=0;cameraRef.current.y=0;}if(detail.type==="reset"){nodesRef.current.forEach(node=>{unpin(node);node.x=node.targetX;node.y=node.targetY;node.vx=0;node.vy=0;});if(motion)simulation.alpha(0.5).restart();fit();}if(detail.type==="focus"){const node=nodeById.get(detail.id);if(node){const scale=Math.max(cameraRef.current.scale,1.25);cameraRef.current.scale=scale;cameraRef.current.x=-node.x*scale;cameraRef.current.y=-node.y*scale;setZoom(Math.round(scale*100));}}};canvas.addEventListener("graph-command",onCommand);
    const down=(event:PointerEvent)=>{const p=point(event),node=hit(p);pointerId=event.pointerId;moved=false;last=p;canvas.setPointerCapture(event.pointerId);if(node){dragged=node;setSelected(node);pin(node,node.x,node.y);if(motion)simulation.alphaTarget(0.2).restart();}else panning=true;};
    const move=(event:PointerEvent)=>{const p=point(event);if(pointerId===event.pointerId){const dx=p.x-last.x,dy=p.y-last.y;if(Math.abs(dx)+Math.abs(dy)>1)moved=true;
      // Only the dragged node itself gets pinned to the pointer. Its children
      // aren't forced to follow in rigid lockstep — the weak forceLink above
      // pulls them along elastically, the same way the demo's link force did,
      // so the branch trails behind with a bit of natural lag instead of
      // sliding as one perfectly rigid unit.
      if(dragged){const w=world(p);pin(dragged,w.x,w.y);}
      else if(panning){cameraRef.current.x+=dx;cameraRef.current.y+=dy;}last=p;}const next=hit(p);if(next?.id!==hoveredRef.current?.id){hoveredRef.current=next;setHovered(next);}};
    const up=(event:PointerEvent)=>{if(pointerId!==event.pointerId)return;if(!moved&&dragged){setSelected(dragged);if(event.detail===2){if(dragged.childCount>0){setDepthLimit(value=>Math.max(value,dragged!.depth+1));setCollapsed(previous=>{const next=new Set(previous);next.has(dragged!.id)?next.delete(dragged!.id):next.add(dragged!.id);return next;});}else openNode(dragged);}}
      if(dragged){unpin(dragged);if(motion)simulation.alphaTarget(0);}
      dragged=null;panning=false;pointerId=null;};
    const wheel=(event:WheelEvent)=>{event.preventDefault();scaleTo(cameraRef.current.scale*(event.deltaY>0?.9:1.1),point(event));};canvas.addEventListener("pointerdown",down);canvas.addEventListener("pointermove",move);canvas.addEventListener("pointerup",up);canvas.addEventListener("wheel",wheel,{passive:false});
    const draw=()=>{context.clearRect(0,0,width,height);const camera=cameraRef.current;context.save();context.translate(width/2+camera.x,height/2+camera.y);context.scale(camera.scale,camera.scale);const shown=new Set(nodesRef.current.filter(visible).map(n=>n.id));context.lineWidth=1/camera.scale;for(const edge of model.structuralEdges){if(!shown.has(edge.sourceId)||!shown.has(edge.targetId))continue;const a=nodeById.get(edge.sourceId),b=nodeById.get(edge.targetId);if(!a||!b)continue;context.strokeStyle="#73798a66";context.beginPath();context.moveTo(a.x,a.y);context.lineTo(b.x,b.y);context.stroke();}if(showConnections){for(const edge of snapshot.relationships){if(!shown.has(edge.sourceId)||!shown.has(edge.targetId))continue;const a=nodeById.get(edge.sourceId),b=nodeById.get(edge.targetId);if(!a||!b)continue;const highlighted=selectedRef.current&&(selectedRef.current.id===edge.sourceId||selectedRef.current.id===edge.targetId);const color=edge.relationshipType==="contradicts"||edge.relationshipType==="blocks"?"#ef7b86":edge.relationshipType==="supports"||edge.relationshipType==="implements"?"#74d6a0":"#9caeff";context.save();context.strokeStyle=color;context.globalAlpha=highlighted?1:.62;context.lineWidth=(highlighted?2.2:1.35)/camera.scale;context.setLineDash([5/camera.scale,4/camera.scale]);const dx=b.x-a.x,dy=b.y-a.y,bend=Math.min(50,Math.hypot(dx,dy)*.16),nx=-dy/(Math.hypot(dx,dy)||1),ny=dx/(Math.hypot(dx,dy)||1);context.beginPath();context.moveTo(a.x,a.y);context.quadraticCurveTo((a.x+b.x)/2+nx*bend,(a.y+b.y)/2+ny*bend,b.x,b.y);context.stroke();context.restore();}}
      const force=forced();for(const node of nodesRef.current.filter(visible)){const isSelected=node.id===selectedRef.current?.id,isHovered=node.id===hoveredRef.current?.id,isMatch=normalized&&(node.name.toLowerCase().includes(normalized)||node.path.toLowerCase().includes(normalized));const dim=normalized&&!force.has(node.id);context.globalAlpha=dim?.25:1;const radius=node.radius*nodeSize/100;context.fillStyle=node.depth===0?"#f5f6fa":colorFor(node.branchId);context.beginPath();context.arc(node.x,node.y,radius+(isSelected?2/camera.scale:0),0,Math.PI*2);context.fill();if(isSelected||isHovered){context.strokeStyle=isSelected?"#fff":"#b9c6ff";context.lineWidth=2/camera.scale;context.stroke();}const always=node.depth<=1,isForced=isSelected||isHovered||isMatch;const showLabel=labels&&(always||isForced||(node.type==="folder"&&camera.scale>=.72)||(node.type==="file"&&camera.scale>=1.22));if(showLabel){context.globalAlpha=1;context.font=`${isForced?600:500} ${Math.max(9,11/camera.scale)}px Inter,system-ui`;context.textAlign="center";context.textBaseline="bottom";context.lineWidth=3/camera.scale;context.strokeStyle="#14151c";context.strokeText(node.name,node.x,node.y-radius-5/camera.scale);context.fillStyle="#eef0f6";context.fillText(node.name,node.x,node.y-radius-5/camera.scale);}}context.restore();context.globalAlpha=1;frame=requestAnimationFrame(draw);};frame=requestAnimationFrame(draw);setTimeout(fit,50);
    return()=>{cancelAnimationFrame(frame);simulation.stop();observer.disconnect();canvas.removeEventListener("graph-command",onCommand);canvas.removeEventListener("pointerdown",down);canvas.removeEventListener("pointermove",move);canvas.removeEventListener("pointerup",up);canvas.removeEventListener("wheel",wheel);};
  },[activeBranches,collapsed,depthLimit,labels,linkStrength,localMode,model,motion,nodeSize,normalized,repelStrength,showConnections,showKnowledge,snapshot.relationships]);

  return <div className={`graph-v2 ${panel?"with-panel":""}`}>
    <div className="graph-stage">
      <div className="graph-search"><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search the entire hierarchy…"/>{normalized&&<div className="search-results">{results.map(node=><button key={node.id} onClick={()=>focus(node)}><b>{node.name}</b><small>{node.path}</small></button>)}{results.length===0&&<p>No graph results</p>}</div>}</div>
      <canvas ref={canvasRef} className="graph" data-hovering={Boolean(hovered)}/>
      <div className="graph-actions"><button title="Zoom out" onClick={()=>command({type:"zoom-out"})}>−</button><span>{zoom}%</span><button title="Zoom in" onClick={()=>command({type:"zoom-in"})}>+</button><i/><button onClick={()=>command({type:"fit"})}>Fit</button><button onClick={()=>command({type:"center"})}>Center</button><button onClick={()=>command({type:"reset"})}>Reset</button></div>
      <div className="graph-help">Folders open on double-click · nearby nodes repel and settle back into their branch</div>
      {selected&&<div className="selection-pill"><span style={{background:colorFor(selected.branchId)}}/><div className="selection-copy"><b>{selected.name}</b><small>{selected.path} · {selected.descendantCount} descendants</small></div>{selected.type!=="vault"&&<button onClick={()=>openNode(selected)}>Open</button>}<button onClick={()=>setSelected(null)}>×</button></div>}
    </div>
    {panel&&<aside className="graph-controls">
      <div className="panel-head"><b>Graph controls</b><button onClick={()=>setPanel(false)}>×</button></div>
      <section><span className="control-title">View</span><div className="mode-grid"><button className={!localMode?"active":""} onClick={()=>setLocalMode(false)}>Atlas</button><button className={localMode?"active":""} disabled={!selected} onClick={()=>setLocalMode(true)}>Local</button><button className={showConnections?"active":""} onClick={()=>setShowConnections(value=>!value)}>Connections</button><button className={showKnowledge?"active":""} onClick={()=>setShowKnowledge(value=>!value)}>Knowledge</button></div><p className="mode-note">Structure first, detail on demand. Relationship overlays never alter hierarchy.</p>{showConnections&&<div className="relationship-legend"><span><i className="positive"/>supports / implements</span><span><i/>references / depends on</span><span><i className="negative"/>blocks / contradicts</span></div>}</section>
      <section><span className="control-title">Display</span><label className="switch-row">Live motion<input type="checkbox" checked={motion} onChange={e=>setMotion(e.target.checked)}/><i/></label><label className="switch-row">Labels<input type="checkbox" checked={labels} onChange={e=>setLabels(e.target.checked)}/><i/></label><label className="range-label">Visible depth <span>{depthLimit}</span></label><input type="range" min="1" max={Math.max(3,...model.nodes.map(node=>node.depth))} value={depthLimit} onChange={e=>setDepthLimit(+e.target.value)}/><label className="range-label">Node size <span>{nodeSize}%</span></label><input type="range" min="70" max="150" value={nodeSize} onChange={e=>setNodeSize(+e.target.value)}/><label className="range-label">Node spacing <span>{repelStrength}%</span></label><input type="range" min="0" max="100" value={repelStrength} onChange={e=>setRepelStrength(+e.target.value)}/><label className="range-label">Hierarchy pull <span>{linkStrength}%</span></label><input type="range" min="30" max="90" value={linkStrength} onChange={e=>setLinkStrength(+e.target.value)}/></section>
      <section><span className="control-title">Projects</span>{branches.map(branch=><label className="group-row" key={branch.id}><input type="checkbox" checked={activeBranches.has(branch.id)} onChange={()=>toggleBranch(branch.id)}/><span style={{background:colorFor(branch.id)}}/>{branch.name}<small>{branch.descendantCount}</small></label>)}</section>
      <section><span className="control-title">Hierarchy</span><div className="hierarchy-buttons"><button onClick={()=>{setDepthLimit(maxDepth);setCollapsed(new Set());}}>Expand all</button><button onClick={()=>{setDepthLimit(maxDepth);setCollapsed(new Set(model.nodes.filter(n=>n.childCount>0&&n.depth>=2).map(n=>n.id)));}}>Collapse to folders</button><button onClick={()=>{setDepthLimit(maxDepth);setCollapsed(new Set(model.nodes.filter(n=>n.type==="folder"&&n.depth>=2&&n.childCount>0).map(n=>n.id)));command({type:"reset"});}}>Reset hierarchy</button></div></section>
    </aside>}
    {!panel&&<button className="open-graph-panel" onClick={()=>setPanel(true)}>Controls</button>}
  </div>;
}
